### PR TITLE
complete application

### PR DESCRIPTION
**Pull request by madhvikokil**
@chetan-bura-cuelogic

### CODE REVIEW

**Comment by chetan-bura-cuelogic** [comment]
1) Folder Structure: for example see below module wise breaking
e.g.
Modules
	Moduel_Name
		Container
		Components
Utility
Assets

2) Naming convention for components and containers
	Need to give proper naming
	
3) CSS files need to move to Assets folder

4) Confirgure ES lint

5) functions name need to be proper not `data` and `data2`
componentDidMount =async()=>{ 
- async is not needed
6) const vs let
7) Remove debugger used in code

8) App.js, the  routes name should be proper

9) Login.js
- Need to use API calls using utility function only
- Optimize form element change events
- Optimize form component

**Comment by chetan-bura-cuelogic** [comment]
1) Remove Bootstrap, use semantic-ui or bootstrap not both
2) Missing ErrorBoundry 
3) Remove console messages.

**Comment by chetan-bura-cuelogic** [comment]
1. Add loaders wherever required .
2. Remove promise from componentDidMount
3. Remove unused variables

**Comment by madhvikokil** [comment]
> 1. Add loaders wherever required. (Project list etc.)
> 2. Remove promise from componentDidMount
> 3. Remove unused variables



> 1. Add loaders wherever required. (Project list etc.)
> 2. Remove promise from componentDidMount
> 3. Remove unused variables

Changes are done

**Comment by chetan-bura-cuelogic** [comment]
Add Project name in the two tables.
Ref:
React App

**Comment by madhvikokil** [comment]
> Add Project name in the two tables.
> Ref:

Added the Project name

**Pull request merged**
